/*
 * TypeA.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin.oneof

interface TypeA {

    val aaa: Long?

    data class C(
        override val aaa: Long? = null,
        val zzz: String? = null
    ) : TypeA

    data class D(
        override val aaa: Long? = null,
        val qqq: String? = null
    ) : TypeA {

        init {
            if (qqq != null)
                require(qqq.isNotEmpty()) { "qqq length < minimum 1 - ${qqq.length}" }
        }

    }

}
