/*
 * Person.java
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.java.person;

import java.util.UUID;

import javax.annotation.Generated;
import net.pwall.json.schema.codegen.test.annotation.DummyClassAnnotation;
import net.pwall.json.schema.codegen.test.annotation.DummyFieldAnnotation;

/**
 * A class to represent a person
 */
@DummyClassAnnotation
@Generated("net.pwall.json.schema.codegen.CodeGenerator")
public class Person {

    private final UUID id;
    private final String name;

    public Person(
            UUID id,
            String name
    ) {
        if (id == null)
            throw new IllegalArgumentException("Must not be null - id");
        this.id = id;
        if (name == null)
            throw new IllegalArgumentException("Must not be null - name");
        this.name = name;
    }

    /**
     * Id of the person
     */
    @DummyFieldAnnotation("id")
    public UUID getId() {
        return id;
    }

    /**
     * Name of the person
     */
    @DummyFieldAnnotation("name")
    public String getName() {
        return name;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other)
            return true;
        if (!(other instanceof Person))
            return false;
        Person typedOther = (Person)other;
        if (!id.equals(typedOther.id))
            return false;
        return name.equals(typedOther.name);
    }

    @Override
    public int hashCode() {
        int hash = id.hashCode();
        return hash ^ name.hashCode();
    }

    public static class Builder {

        private UUID id;
        private String name;

        public Builder withId(UUID id) {
            this.id = id;
            return this;
        }

        public Builder withName(String name) {
            this.name = name;
            return this;
        }

        public Person build() {
            return new Person(
                    id,
                    name
            );
        }

    }

}
