/*
 * Person.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin.person

import java.util.UUID

import net.pwall.json.schema.codegen.test.annotation.DummyClassAnnotation
import net.pwall.json.schema.codegen.test.annotation.DummyFieldAnnotation

/**
 * A class to represent a person
 */
@DummyClassAnnotation
data class Person(
    /** Id of the person */
    @DummyFieldAnnotation("id")
    val id: UUID,
    /** Name of the person */
    @DummyFieldAnnotation("name")
    val name: String
)
