/*
 * TestDerivedWithValidation1.java
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.java;

/**
 * Add const and default to enum and minimum range on int and maximum length on string
 */
public class TestDerivedWithValidation1 extends TestBaseWithValidation {

    private final String payload;

    public TestDerivedWithValidation1(
            Type type,
            int quantity,
            String name,
            String payload
    ) {
        super(type, quantity, name);
        if (type != Type.FIRST)
            throw new IllegalArgumentException("type not constant value FIRST - " + type);
        if (quantity < 0)
            throw new IllegalArgumentException("quantity < minimum 0 - " + quantity);
        if (name.length() > 30)
            throw new IllegalArgumentException("name length > maximum 30 - " + name.length());
        if (payload == null)
            throw new IllegalArgumentException("Must not be null - payload");
        this.payload = payload;
    }

    public String getPayload() {
        return payload;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other)
            return true;
        if (!(other instanceof TestDerivedWithValidation1))
            return false;
        if (!super.equals(other))
            return false;
        TestDerivedWithValidation1 typedOther = (TestDerivedWithValidation1)other;
        return payload.equals(typedOther.payload);
    }

    @Override
    public int hashCode() {
        int hash = super.hashCode();
        return hash ^ payload.hashCode();
    }

}
