/*
 * TestApTrueConst.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin

/**
 * Test use of additionalProperties true with const number of properties.
 */
class TestApTrueConst(
    private val cg_map: Map<String, Any?>
) : Map<String, Any?> by cg_map {

    init {
        require(cg_map.size == 3) { "Number of properties != constant 3 - ${cg_map.size}" }
    }

    override fun toString(): String = "TestApTrueConst(${cg_map.entries.joinToString { "${it.key}=${it.value}" }})"

    override fun equals(other: Any?): Boolean = this === other || other is TestApTrueConst && cg_map == other.cg_map

    override fun hashCode(): Int = cg_map.hashCode()

}
