/*
 * TestPolymorphicGroup3.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin

/**
 * Test generation of even more complex group of polymorphic classes.
 */
interface TestPolymorphicGroup3 {

    val base: String

}
