/*
 * TestApNestedFalse.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin

/**
 * Test use of nested additionalProperties false.
 */
data class TestApNestedFalse(
    val nested: Nested
) {

    class Nested {

        override fun toString(): String = "Nested()"

        override fun equals(other: Any?): Boolean = this === other || other is Nested

        override fun hashCode(): Int = 1

    }

}
