/*
 * TestAdditionalPropertiesSchemaValid.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin

/**
 * Test use of additionalProperties with schema with validations.
 */
class TestAdditionalPropertiesSchemaValid(
    private val cg_map: Map<String, String>
) : Map<String, String> by cg_map {

    init {
        cg_map.entries.forEach { (key, value) ->
            require(value.isNotEmpty()) { "$key length < minimum 1 - ${value.length}" }
        }
    }

    override fun toString() = buildString {
        append("TestAdditionalPropertiesSchemaValid(")
        if (cg_map.isNotEmpty()) {
            var count = 0
            cg_map.entries.forEach { (key, value) ->
                append(key)
                append('=')
                append(value)
                if (++count < cg_map.size)
                    append(", ")
            }
        }
        append(')')
    }

    override fun equals(other: Any?): Boolean = this === other || other is TestAdditionalPropertiesSchemaValid && cg_map == other.cg_map

    override fun hashCode(): Int = cg_map.hashCode()

}
