/*
 * TestDerivedWithValidation0.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin

/**
 * No additional validations
 */
class TestDerivedWithValidation0(
    type: Type,
    quantity: Int,
    name: String,
    val payload: String
) : TestBaseWithValidation(type, quantity, name) {

    override fun equals(other: Any?): Boolean = this === other || other is TestDerivedWithValidation0 &&
            super.equals(other) &&
            payload == other.payload

    override fun hashCode(): Int = super.hashCode() xor
            payload.hashCode()

    override fun toString() = "TestDerivedWithValidation0(type=$type, quantity=$quantity, name=$name, payload=$payload)"

    fun copy(
        type: Type = this.type,
        quantity: Int = this.quantity,
        name: String = this.name,
        payload: String = this.payload
    ) = TestDerivedWithValidation0(type, quantity, name, payload)

    operator fun component4() = payload

}
