/*
 * TestApNestedTrue.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin

/**
 * Test use of nested additionalProperties true.
 */
data class TestApNestedTrue(
    val nested: Nested
) {

    class Nested(
        private val cg_map: Map<String, Any?>
    ) : Map<String, Any?> by cg_map {

        override fun toString() = buildString {
            append("Nested(")
            if (cg_map.isNotEmpty()) {
                var count = 0
                cg_map.entries.forEach { (key, value) ->
                    append(key)
                    append('=')
                    append(value)
                    if (++count < cg_map.size)
                        append(", ")
                }
            }
            append(')')
        }

        override fun equals(other: Any?): Boolean = this === other || other is Nested && cg_map == other.cg_map

        override fun hashCode(): Int = cg_map.hashCode()

    }

}
