/*
 * TestUpperCaseName.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin

/**
 * Test use of names starting with upper-case - example supplied by GitHub user ilkkapoutanen-61n.
 */
data class TestUpperCaseName(
    val widget: Widget? = null
) {

    data class Widget(
        val isFrobbed: Boolean? = null
    )

}
