/*
 * TestAdditionalPropertiesSchemaExtra3.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin

/**
 * Test use of additionalProperties with schema with nullable extra fields.
 */
class TestAdditionalPropertiesSchemaExtra3(
    private val cg_map: Map<String, Any?>
) : Map<String, Any?> by cg_map {

    init {
        require(cg_map.containsKey("extra")) { "required property missing - extra" }
        require(cg_map["extra"] is String) { "extra is not the correct type, expecting String" }
        (cg_map["extra"] as String).let { extra ->
            require(extra.isNotEmpty()) { "extra length < minimum 1 - ${extra.length}" }
        }
        if (cg_map.containsKey("extra2")) {
            require(cg_map["extra2"] is Int?) { "extra2 is not the correct type, expecting Int?" }
            (cg_map["extra2"] as Int?)?.let { extra2 ->
                require(extra2 in 0..99) { "extra2 not in range 0..99 - $extra2" }
            }
        }
        cg_map.entries.forEach { (key, value) ->
            if (key != "extra" && key != "extra2") {
                require(value is Int) { "$key is not the correct type, expecting Int" }
                require(value in 0..9999) { "$key not in range 0..9999 - $value" }
            }
        }
    }

    /** Extra field */
    val extra: String by cg_map

    /** Extra field 2 */
    val extra2: Int?
        get() = cg_map["extra2"] as Int?

    override fun toString(): String = "TestAdditionalPropertiesSchemaExtra3(${cg_map.entries.joinToString { "${it.key}=${it.value}" }})"

    override fun equals(other: Any?): Boolean = this === other || other is TestAdditionalPropertiesSchemaExtra3 && cg_map == other.cg_map

    override fun hashCode(): Int = cg_map.hashCode()

}
