/*
 * TestNullableNestedClass.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin

data class TestNullableNestedClass(
    val error: ErrorInfo? = null,
    val name: String
) {

    data class ErrorInfo(
        val code: Long,
        val message: String
    )

}
