/*
 * TestAdditionalPropertiesSchema1.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin

import java.time.LocalDate

/**
 * Test use of additionalProperties with schema.
 */
class TestAdditionalPropertiesSchema1(
    private val cg_map: Map<String, LocalDate>
) : Map<String, LocalDate> by cg_map {

    override fun toString() = buildString {
        append("TestAdditionalPropertiesSchema1(")
        if (cg_map.isNotEmpty()) {
            var count = 0
            cg_map.entries.forEach { (key, value) ->
                append(key)
                append('=')
                append(value)
                if (++count < cg_map.size)
                    append(", ")
            }
        }
        append(')')
    }

    override fun equals(other: Any?): Boolean = this === other || other is TestAdditionalPropertiesSchema1 && cg_map == other.cg_map

    override fun hashCode(): Int = cg_map.hashCode()

}
