/*
 * TestCustomDecimalClass.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin

import net.pwall.json.schema.codegen.test.kotlin.decimal.DecimalClass

/**
 * Test custom decimal class.
 */
data class TestCustomDecimalClass(
    val aaa: DecimalClass,
    val bbb: DecimalClass
) {

    init {
        require(aaa >= DecimalClass.ZERO) { "aaa < minimum 0 - $aaa" }
        require(bbb <= cg_dec0) { "bbb > maximum 1.0 - $bbb" }
    }

    companion object {
        private val cg_dec0 = DecimalClass.ONE
    }

}
