/*
 * TypeA.java
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.java.oneof;

public interface TypeA {

    long getAaa();

    public static class C implements TypeA {

        private final long aaa;
        private final String zzz;

        public C(
                long aaa,
                String zzz
        ) {
            this.aaa = aaa;
            this.zzz = zzz;
        }

        @Override
        public long getAaa() {
            return aaa;
        }

        public String getZzz() {
            return zzz;
        }

        @Override
        public boolean equals(Object cg_other) {
            if (this == cg_other)
                return true;
            if (!(cg_other instanceof C))
                return false;
            C cg_typedOther = (C)cg_other;
            if (aaa != cg_typedOther.aaa)
                return false;
            return zzz == null ? cg_typedOther.zzz == null : zzz.equals(cg_typedOther.zzz);
        }

        @Override
        public int hashCode() {
            int hash = (int)aaa;
            return hash ^ (zzz != null ? zzz.hashCode() : 0);
        }

    }

    public static class D implements TypeA {

        private final long aaa;
        private final String qqq;

        public D(
                long aaa,
                String qqq
        ) {
            this.aaa = aaa;
            if (qqq != null && qqq.length() < 1)
                throw new IllegalArgumentException("qqq length < minimum 1 - " + qqq.length());
            this.qqq = qqq;
        }

        @Override
        public long getAaa() {
            return aaa;
        }

        public String getQqq() {
            return qqq;
        }

        @Override
        public boolean equals(Object cg_other) {
            if (this == cg_other)
                return true;
            if (!(cg_other instanceof D))
                return false;
            D cg_typedOther = (D)cg_other;
            if (aaa != cg_typedOther.aaa)
                return false;
            return qqq == null ? cg_typedOther.qqq == null : qqq.equals(cg_typedOther.qqq);
        }

        @Override
        public int hashCode() {
            int hash = (int)aaa;
            return hash ^ (qqq != null ? qqq.hashCode() : 0);
        }

    }

}
