/*
 * TypeB.java
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.java.oneof;

public class TypeB implements TypeA {

    private final long aaa;
    private final String xxx;

    public TypeB(
            long aaa,
            String xxx
    ) {
        this.aaa = aaa;
        if (xxx == null)
            throw new IllegalArgumentException("Must not be null - xxx");
        this.xxx = xxx;
    }

    @Override
    public long getAaa() {
        return aaa;
    }

    public String getXxx() {
        return xxx;
    }

    @Override
    public boolean equals(Object cg_other) {
        if (this == cg_other)
            return true;
        if (!(cg_other instanceof TypeB))
            return false;
        TypeB cg_typedOther = (TypeB)cg_other;
        if (aaa != cg_typedOther.aaa)
            return false;
        return xxx.equals(cg_typedOther.xxx);
    }

    @Override
    public int hashCode() {
        int hash = (int)aaa;
        return hash ^ xxx.hashCode();
    }

    public static class Builder {

        private long aaa;
        private String xxx;

        public Builder withAaa(long aaa) {
            this.aaa = aaa;
            return this;
        }

        public Builder withXxx(String xxx) {
            this.xxx = xxx;
            return this;
        }

        public TypeB build() {
            return new TypeB(
                    aaa,
                    xxx
            );
        }

    }

}
