/*
 * @(#) CodeGeneratorTestUtil.kt
 *
 * json-kotlin-schema-codegen  JSON Schema Code Generation
 * Copyright (c) 2020, 2021 Peter Wall
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package net.pwall.json.schema.codegen

import java.io.File
import kotlin.test.fail

import java.io.StringWriter

object CodeGeneratorTestUtil {

    const val packageName = "net.pwall.json.schema.codegen.test.kotlin"
    val packageDirs = packageName.split('.')
    val dirs = listOf("com", "example")

    fun resultFile(filename: String): String =
        File("src/test/kotlin/net/pwall/json/schema/codegen/test/kotlin/$filename.kt").reader().readText()

    fun createHeader(name: String, comment: String? = null) =
"""/*
 * $name
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.${comment?.let { """
 *
 * $it""" } ?: ""}
 */
"""

    fun outputCapture(expectedTargetFileName: TargetFileName, stringWriter: StringWriter): OutputResolver =
            { targetFileName ->
        if (targetFileName == expectedTargetFileName)
            stringWriter
        else
            fail("Output resolver fail - $targetFileName")
    }

    fun outputCapture(vararg outputDetails: OutputDetails): OutputResolver = { targetFileName ->
                locateWriter(outputDetails.asList(), targetFileName)
    }

    private fun locateWriter(outputDetails: List<OutputDetails>, targetFileName: TargetFileName): StringWriter {
        for (entry in outputDetails)
            if (targetFileName == entry.expectedTargetFileName)
                return entry.stringWriter
        fail("Output resolver fail - $targetFileName")
    }

    data class OutputDetails(
        val expectedTargetFileName: TargetFileName,
        val stringWriter: StringWriter = StringWriter(),
    ) {

        fun output() = stringWriter.toString()

    }

}
