/*
 * TestBaseEmptyDerived.java
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.java.basederived;

/**
 * Test base with empty derived class.
 */
public class TestBaseEmptyDerived extends TestBase {

    public TestBaseEmptyDerived(
            String aaa
    ) {
        super(aaa);
    }

    @Override
    public boolean equals(Object cg_other) {
        if (this == cg_other)
            return true;
        if (!(cg_other instanceof TestBaseEmptyDerived))
            return false;
        if (!super.equals(cg_other))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    public static class Builder {

        private String aaa;

        public Builder withAaa(String aaa) {
            this.aaa = aaa;
            return this;
        }

        public TestBaseEmptyDerived build() {
            return new TestBaseEmptyDerived(
                    aaa
            );
        }

    }

}
