/*
 * PhoneContact.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package net.pwall.json.schema.codegen.test.kotlin.poly6

import net.pwall.json.schema.codegen.test.kotlin.TestPolymorphicGroup6

class PhoneContact(
    override val extraProperty: String,
    override val contactType: String
) : ContactBase(contactType), TestPolymorphicGroup6 {

    init {
        require(contactType == cg_str0) { "contactType not constant value $cg_str0 - $contactType" }
    }

    override fun equals(other: Any?): Boolean = this === other || other is PhoneContact &&
            super.equals(other)

    override fun hashCode(): Int = super.hashCode()

    override fun toString() = "PhoneContact(extraProperty=$extraProperty, contactType=$contactType)"

    fun copy(
        extraProperty: String = this.extraProperty,
        contactType: String = this.contactType
    ) = PhoneContact(extraProperty, contactType)

    companion object {
        private const val cg_str0 = "PHONE"
    }

}
